<?php include $_SERVER['DOCUMENT_ROOT'] . "/database/amzi_connect.php"; ?>
<?php

// get_subscription.php is used from version 9-5 on.

// Campaign Manager stuff for adding to our mailing lists
	//Relative path to CMBase.php. This example assumes the file is in the same folder
	require_once('CMBase.php');
	
	//Your API Key. Go to http://www.campaignmonitor.com/api/required/ to see where to find this and other required keys
	
	$api_key = 'bafb8a9c669a47592624cdca320c5c1a';
	$client_id = null;
	$campaign_id = null;
	//$list_id = 'a8eebb9f1c9acc01266327fb10979e61';   // Sample List
	$list_id = '2b08490fc6928a01c7345aecc70cd572';   // AmziNews
	
	$cm = new CampaignMonitor( $api_key, $client_id, $campaign_id, $list_id );
	
	//Optional statement to include debugging information in the result
	//$cm->debug_level = 1;
	
	//$xemail = 'three@gg.com';
	//$xname = 'Three';
	//$result = $cm->subscriberAdd($xemail, $xname);

	//Optional statement to include debugging information in the result
	//$cm->debug_level = 1;


//mail($mailee, 'Diagnostic 2 cm', 'CM done', '');


// Clean up all the parameters up-front
$freference = trim(mysql_real_escape_string($_REQUEST['reference']));
$fenterprisename = trim(mysql_real_escape_string($_REQUEST['enterprisename']));
$fusername = trim(mysql_real_escape_string($_REQUEST['username']));
$fcomputer = trim(mysql_real_escape_string($_REQUEST['computer']));
$fkey = trim(mysql_real_escape_string($_REQUEST['key'])); 
$femail = trim(mysql_real_escape_string($_REQUEST['email']));
$fact = trim(mysql_real_escape_string($_REQUEST['act']));

//mail($mailee, 'Diagnostic 3 cleanup', 'CM done', '');

// where we were called from
$addr = $_SERVER['REMOTE_ADDR'];
$host = gethostbyaddr($addr);

//mail($mailee, 'Diagnostic 4 host', $host, '');


// Get today's year
date_default_timezone_set("UTC");
$date = getdate();
$today = $date['year'] . '-' . $date['mon'] . '-' . $date['mday'];

$msg =  " reference = $freference \n";
$msg .= " enterprisename = $fenterprisename \n";
$msg .= " username = $fusername \n";
$msg .= " computer = $fcomputer \n";
$msg .= " key = $fkey \n";
$msg .= " email = $femail \n";
$msg .= " act = $fact \n";
$msg .= " addr = $addr \n";
$msg .= " host = $host \n";
$msg .= " today = $today \n";

//mail($mailee, 'get_subscription', $addr . " " . $host . "\n" . $msg, '');

//mail($mailee, 'Diagnostic 5 msg', $msg, '');


// Filter out bad stuff
// regular expression / brackets, ^ start of string, $ end of string, [..]+ these characters in between.
$exp = "/^[0-9-]+$/";
if (! preg_match($exp, $freference)) die('ERROR: Invalid reference number');

if (!filter_var($femail, FILTER_VALIDATE_EMAIL)) die('ERROR: Invalid email format');

$reference = $freference;

//mail($mailee, 'Diagnostic 6 into eval', 'starting reference', '');

// reference == 0 means it's an evaluation
if ($reference == 0)
{
	//mail($mailee, 'Diagnostic 7 in ev', 'In evaluation', '');
	
	// first time call from activate, key is blank, just return that it's an EVAL
	if ($fkey == '')
	{
		$product = "EVAL";
		$dbsubscriptionDate = "";
		
	  //mail($mailee, 'Diagnostic 8 about to die', 'In evaluation', '');
		
		
		die("Result:$dbsubscriptionDate:$product:");
	}
	// we've got a key, so it's the second call.  Now the key could have been generated by
	// by the activation software, or it could have been entered by the user.  If we generated it
	// the user doesn't know it yet, so email to him/her.  If they entered it, they got it
	// from the email so set them up.
	else
	{

		if ($fact == "no")
		{
	    //mail($mailee, 'Diagnostic 9a user email', 'send act in email', '');
			// nice message about email, and send email
			$msg = 'NOTICE: You will receive your evaluation activation code in an e-mail. ' .
				'Start the activation again when you get it and enter the activation code.';
			mail($femail, 'Amzi! Activation Code', 'Your Amzi! evaluation activation code is: ' .
				$fkey . ' . Use it to activate the software', '');
			mysql_close($link);
	    //mail($mailee, 'Diagnostic 9a2 dying msg', $msg, '');
			die($msg);
		}
		else
		{
			//mail($mailee, 'Diagnostic 9b', 'user got act from his email', '');

			$query = "INSERT INTO evaluations (email, name, computer, userkey, evaluationDate) ";
			$query .= "VALUES('" . $femail . "', '" . $fusername . "', '"
					 . $fcomputer . "', '" . $fkey . "', '" . $today . "')";
			mail($mailee,
				"Evaluation: " . $fusername,
				$query . "\n",
				'');
			$result = mysql_query($query);
			if (!$result) {
				$msg = 'ERROR: Failure to update evaluations';
				die($msg);
			}
			//Update our mailing list
			$result = $cm->subscriberAdd($femail, $fusername);
			if($result['Result']['Code'] != 0)
				mail($mailee, 'Error: CM Eval Add', $femail . ' ' . $fusername, '');

			exit("Result:OK:OK:");

		}

	}
}
else
{
	//mail($mailee, 'Diagnostic 7b ref not zero', 'not zero', '');
}

//mail($mailee, 'Diagnostic 10 ev done', 'eval done', '');  // got here

//mail(mailee, 'not evaluation', 'not evaluation', '');

// If you want to make this thread-safe,
// Lock the table for write first using LOCK TABLES xx WRITE and then execute the SELECT ... FOR UPDATE statement

// Get the sales record by reference number
//$query = sprintf("SELECT transactionDate, reference, title, firstName, lastName, email, contractId, contractName, productName, productId, quantity, usedCount, keyDate, allowDomain, priorPurchase FROM sales WHERE reference='%s' FOR UPDATE", $reference);
$query = sprintf("SELECT enterpriseName, enterpriseDomain, productID, subscriptionStartDate from enterprises where reference = '%s'", $reference);

$result = mysql_query($query);

//mail($mailee, 'Diagnostic 4', 'Selected from enterprises', '');

if ($result && mysql_num_rows($result) > 0) {
	// An enterprise activation
	
	// Save a bunch of information from the sales record for key checking and generation
	while ($row = mysql_fetch_assoc($result)) {
		$dbenterpriseName = $row['enterpriseName'];
		$dbenterpriseDomain = $row['enterpriseDomain'];
		$dbsubscriptionDate = $row['subscriptionStartDate'];
		$dbproductid = $row['productID'];
	}
	
	if ( strcmp(soundex($fenterprisename), soundex($dbenterpriseName)) != 0 ) {
		$msg = 'The enterprise name does not match that in DB for the reference number and name -- '
		 . $reference . ' ' . $fenterprisename . ' .';
		mail($mailee, 'Error: Bad Enterprise Name ', $fenterprisename . ' user \= db ' . $dbenterpriseName, '');
		mysql_close($link);
		die($msg);
	}
	
	$query = sprintf("SELECT * FROM enterprises WHERE reference = '%s'
	     AND CURDATE() < DATE_ADD(subscriptionStartDate, INTERVAL 1 YEAR)", $reference);
    $result = mysql_query($query);
	if (!$result || mysql_num_rows($result) == 0) {
		$msg = 'Maintenance and support for your organization has expired.  Please have your system administator renew maintenance so you can install updates for the upcoming year.';
		mail($mailee, 'Error: enterprise maintenance expired',  'Reference = ' . $reference, '');
		mysql_close($link);
		die($msg);
	}
	
	if ( strpos($host, $dbenterpriseDomain) == 0 ) {
	   if ( strpos($femail, $dbenterpriseDomain) == 0 ) {
	   // nasty error
	   		$msg = "You must activate your organization's license using the enterprise domain, "
				 . $dbenterpriseDomain .
				', either by connecting from it or having it in your email address.';
			$mailmsg = 'Activation error: Enterprise Name = ' . $dbenterpriseName .
				' Enterprise Domain = ' . $dbenterpriseDomain .
				' User Name = ' . $fusername .
				' Computer = ' . $fcomputer .
				' User Domain = ' . $host .
				' User eMail = ' . $femail ;
			mail($mailee, 'Error: Bad domain', $mailmsg, '');
	   		mysql_close($link);
	   		die($msg);
	   }
	   else {
	   		if (strcmp($fact, "no") == 0 && $fkey != NULL && strlen($fkey) > 0) {
	   		// nice message about email, and send email
	   			$msg = 'NOTICE: You are not connecting from the enterprise domain, ' .
	   				'so your activation code is being sent by e-mail. ' .
					'Start the activation again when you get it and enter the activation code.';
				mail($femail, 'Amzi! Activation Code', 'Your Amzi! activation code is: ' .
					$fkey . '. Use it to activate the software', '');
	   			mysql_close($link);
	   			die($msg);
			}
	   }
	}
	// all enterprise licenses are professional
	if ($dbproductid == 402740)
		$product = "ARPRO";
	else
		$product = "APLS";
}
else {
	// try the individuals
	$query = sprintf("SELECT name, email, contractID, subscriptionStartDate from individuals where reference = '%s'", $reference);
	$result = mysql_query($query);
	
//mail($mailee, 'Diagnostic 5', 'selected from individuals', '');  // got here
	
	if (!$result || mysql_num_rows($result) == 0) {
		$msg = 'The reference number ' . $reference . ' cannot be found in the database.';
		if ($reference != 0) mail($mailee, 'DB Error', $msg, '');
		mysql_close($link);
		die($msg);
	}
	
//mail($mailee, 'Diagnostic 5a', 'result OK', '');


	// Save a bunch of information from the sales record for key checking and generation
	while ($row = mysql_fetch_assoc($result)) {
		$iname = $row['name'];
		$icontract = $row['contractID'];
		$dbsubscriptionDate = $row['subscriptionStartDate'];
	}

//mail($mailee, 'Diagnostic 5b', 'fetched stuff', '');


	if ( strcmp(soundex($fusername), soundex($iname)) != 0 ) {
		$msg = 'The user name given, ' . $fusername . ', does not match that in DB for the reference number -- ' .
			$reference . ' .';
		mail($mailee, 'DB Error', $msg, '');
		mysql_close($link);
		die($msg);
	}
	
	$query = sprintf("SELECT * FROM individuals WHERE reference = '%s'
	     AND CURDATE() < DATE_ADD(subscriptionStartDate, INTERVAL 1 YEAR)", $reference);
	$result = mysql_query($query);
	if (!$result || mysql_num_rows($result) == 0) {
		$msg = 'Maintenance and support has expired. Please renew your license at www.amzi.com to be able to install new releases for the upcoming year.';
		mail($mailee, 'Error: Expired individual maintenance ',  'Reference = ' . $reference, '');
		mysql_close($link);
		die($msg);
	}

//mail($mailee, 'Diagnostic 5c', 'soundexed', '');

	$dbenterpriseName = "self";
	
	// renewal and initial versions of each contract for Amzi! 8 Individual
	// and ARulesXL Individual
	if ($icontract == 2314668 || $icontract == 2291356) $product = "APXPC";
	else if ($icontract == 2314670 || $icontract == 2291358) $product = "APSPC";
	else if ($icontract == 2314672 || $icontract == 2291360) $product = "AP1PC";
	else if ($icontract == 2400146 || $icontract == 2400156) $product = "ARPRO";
	else if ($icontract == 2400152 || $icontract == 2400154) $product = "ARSTD";
	else if ($icontract == 2871976) $product = "APLS";
	else $product = "unknown";
	
	// make them all full versions now
	if ($product == "APXPC" || $product == "APSPC" || $product == "AP1PC")
		$product = "APLS";
}

// The first time this is called, the $fkey is "".  This is because the key needs the
// subscription start date to build a key.  It will be called again with the key, which,
// if necessary, can be emailed to the user instead.
if ($fkey == NULL || strlen($fkey) == 0) {
   mysql_close($link);
   die("Result:$dbsubscriptionDate:$product:");
}

$query = 'INSERT INTO activations (userID, reference, ';
$query .= 'username, enterprise, email, host, userkey, computer) ';
$query .= "VALUES('NULL', '";
$query .= $reference . "', '" . $fusername . "', '" . $dbenterpriseName . "', '";
$query .= $femail . "', '" . $host . "', '" . $fkey . "', '" . $fcomputer . "')";

if ($dbenterpriseName == "self") {
	mail($mailee,
		"Activation: " . $fusername,
		$query . "\n",
		'');

}
else {
	mail($mailee,
		"Activation: " . $dbenterpriseName . " -- " . $fusername,
		$query . "\n",
		'');
}


$result = mysql_query($query);

//mail($mailee, 'Diagnostic 7', 'Did the insert', '');

if (!$result) {
	$msg = 'Unable to update database -- Please contact Amzi! tech support.';
	mail($mailee, $msg, $query . "\n" . mysql_error(), '');
	mysql_close($link);
	die($msg);
}

	//$xemail = 'four@gg.com';
	//$xname = 'Four';
	//$result = $cm->subscriberAdd($xemail, $xname);
	//$xemail = $femail;
	//$xname = $fusername;
	$cmresult = $cm->subscriberAdd($femail, $fusername);

//mail($mailee, "Before CM", $femail . ' ' . $fusername);
	//Update our mailing list
	//$cm = new CampaignMonitor( $api_key, $client_id, $campaign_id, $list_id );
//mail($mailee, "Twixt CM", $femail . ' ' . $fusername . ' ' . $cm);
	//$result = $cm->subscriberAdd($femail, $fusername);
//mail($mailee, "Tween CM", $femail . ' ' . $fusername . ' ' . $result);
	if ($cmresult['Result']['Code'] != 0) {
		mail($mailee, 'Error: CM Activation Add', $femail . ' ' . $fusername, '');
		}
		
//mail($mailee, "After CM", $xemail . ' ' . $xusername);


mysql_close($link);

//mail($mailee, 'Diagnostic 8', 'Closed the DB, ready to go home', '');

// could use echo "OK"; as well

exit("Result:OK:OK:");
	
// NOTE! The spacing below is very important as it returns newlines around the key
?>
